In [21]:
#Ejercicio 1 terminado
import numpy as np

p = np.array([[1,2,4],[0,0,0],[0,6,8]])
print(p)

p1 = np.array(p[:, 0])
# p1 = np.array([p[0][0],p[1][0],p[2][0]]) #otra manera de coger la primera columna

for index, value in enumerate(p1):
    if value==0:
        p1[index]=7
        
print("array cambiado: ")
print(p1)

# Escribe tu código aquí debajo

[[1 2 4]
 [0 0 0]
 [0 6 8]]
array cambiado: 
[1 7 7]


In [17]:
#usando enumarate
for index, value in enumerate(v):
    print("[", index,"]",value)

[ 0 ] 0
[ 1 ] -1


In [2]:
# --------------------------------------------------------

X = np.array([[1,2,3],[4,5,6],[7,8,9]])
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
#para acceder a filas y columnas

print(str(X[0][0])+" "+str(X[0][1])+" "+str(X[0][2])) 
print(str(X[1][0])+" "+str(X[1][1])+" "+str(X[1][2])) 
print(str(X[2][0])+" "+str(X[2][1])+" "+str(X[2][2])) 

print("primera columna")
print(str(X[0][0])+" "+str(X[1][0])+" "+str(X[2][0])) 

1 2 3
4 5 6
7 8 9
primera columna
1 4 7


In [4]:
espacio1 = np.arange(0,16,2)
print(espacio1)

espacio2 = np.linspace(0,10,5)
print(espacio2)



[ 0  2  4  6  8 10 12 14]
[ 0.   2.5  5.   7.5 10. ]


In [5]:
p = np.array([[1,1,1],[2,0,0],[0,6,8]])
print("mi matriz p:")
print(p)
# print(p.size)
# print(p.shape)

print(p[2][1]) #FILA 2, COLUMNA 1
print(p[2:][0]) #0: FILA 2 en adelante, columna 0
print(p[0:][2]) #0: FILA 0 en adelante, columna 2

print("mi prueba")
print(p[2][2:]) # fila 0, columna 2 ENTERA en adelante
print(p[2][1:]) #fila 0, columna 1 ENTERA en adelante
print(p[2][0:])

print("mi prueba 2")
print(p[0][0])
print(p[1][0])
print(p[2][0])

print("imprimiendo columnas")
print(p[:, 0])
print(p[:, 1])
print(p[:, 2])
#cuando tengo un 0: en la columna, la [fila] es la que va a determinar que numeros se imprimen

mi matriz p:
[[1 1 1]
 [2 0 0]
 [0 6 8]]
6
[0 6 8]
[0 6 8]
mi prueba
[8]
[6 8]
[0 6 8]
mi prueba 2
1
2
0
imprimiendo columnas
[1 2 0]
[1 0 6]
[1 0 8]


In [28]:
array1 = np.ones(10)
print(array1)
print(array1*4)


identidad = np.eye(4)
print(identidad)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
#ejercicio 2 hecho a pelo
import numpy as np
def d(v, u):
    a = u[0]-v[0] #resta 
    b = u[1]-v[1]
    a = a**2 #elevado al cuadrado
    b = b**2
    c = a+b #suma de todo
    c = c**0.5 #raiz cuadrado final
    return c
        
v = np.array([0,-1])
u = np.array([0,1])

print(d(v,u))

d(v,u) # El resultado debería de ser 2

    

2.0


2.0

In [16]:
#ejercicio 2 mejorado automatizado
import numpy as np
def d(v, u):
    lista=[]
    for x in range(np.size(v)): #resta
        lista.append(u[x]-v[x])
    
    for x in range(np.size(v)): #elevado al cuadrado
        lista[x] = lista[x]**2

    num3 = sum(lista) #suma de todo
    num3 = num3**0.5 #raiz cuadrado final    
    return num3
            
v = np.array([0,-1])
u = np.array([0,1])

print("mi resultado:",d(v,u))
d(v,u) # El resultado debería de ser 2

mi resultado: 2.0


2.0

In [15]:
#ejer 3 hecho a pelo
import numpy as np

def cos(v, u):
    #producto escalar completo
    a = u[0]*v[0]
    b = u[1]*v[1]
    c = a + b #FINAL
    
    #norma del vector
    num1 = u[0]**2
    num2 = u[1]**2
    resul1 = num1+num2
    resul1 = resul1**0.5
    
    num3 = v[0]**2
    num4 = v[1]**2
    resul2 = num3 + num4
    resul2 = resul2**0.5
    
    #producto de las 2 normas del vector
    resul3 = resul1*resul2 #FINAL
    
    #cociente del producto escalar y las normas del vector
    final = c / resul3
    return final

v = np.array([0,-1])
u = np.array([0,1])

print("resultado:",cos(v,u))

cos(v,u)  # El resultado debería de ser -1.0

resultado: -1.0


-1.0

In [14]:
#ejer 3 mejorado automatizado
import numpy as np

def cos(v, u):
    lista=[] #las listas tienen que estar dentro de la funcion
    normalV=[]
    normalU=[]
    
    for i in range (np.size(v)): #producto escalar 
        lista.append(u[i]*v[i])
    sumaLista = sum(lista)
    
    for i in range(np.size(v)): #normal del vector
        normalV.append(v[i]**2)
        normalU.append(u[i]**2)
    normalV = sum(normalV) 
    normalV = normalV**0.5
    normalU = sum(normalU)
    normalU = normalU**0.5
    
    #producto de las 2 normas del vector
    producto = normalV * normalU #FINAL
    
    #cociente del producto escalar y las normas del vector
    final = sumaLista / producto
    return final

v = np.array([0,-1])
u = np.array([0,1])

print("resultado:",cos(v,u))

cos(v,u)  # El resultado debería de ser -1.0

resultado: -1.0


-1.0

In [5]:
#prueba de que una variable cambia de tipo al usar el metodo sum()
lista2 = [1,2,2,3]
print("1",type(lista2))

lista2 = sum(lista2)
print("2",type(lista2))

print(lista2)
print("3",type(lista2))

1 <class 'list'>
2 <class 'int'>
8
3 <class 'int'>


In [58]:
#ejer 4

import numpy as np
#hemos borrado las funciones, cambia el codígo siguiente

def media(lista): #funcion que calcula la media, usando funcion de np
    a = np.array([])
    a = np.append(a, lista) #meto los numeros de la lista de un array
    media = a.mean()
    return media
    
def DES(lista):
    b = np.array([])
    b = np.append(b, lista)
    desviacion = b.std()
    return desviacion
    
lista = [4, 1, 11, 13, 2, 7]

print("media:",media(lista))
print("desviacion",DES(lista))

print(lista)
print("media = "+str(media(lista))+" \u00B1 "+str(DES(lista)))

media: 6.333333333333333
desviacion 4.459696053419884
[4, 1, 11, 13, 2, 7]
media = 6.333333333333333 ± 4.459696053419884


In [54]:
#como hacer append a una lista
import numpy as np

lista = [4, 1, 11, 13, 2, 7]
array=np.array([])
e = np.append(array, lista)
print("mi array",e)


p = np.array([10,20,20])
a = np.array([2,2,2])
print("antes")
print(p)
print(a)


c = np.append(p, a)
print("despues")
print(p)
print(a)
print(c)



mi array [ 4.  1. 11. 13.  2.  7.]
antes
[10 20 20]
[2 2 2]
despues
[10 20 20]
[2 2 2]
[10 20 20  2  2  2]


In [29]:
#EJER 5

import numpy as np

array = np.array([])
print(array)

for i in range(10):
    array = np.append(array, 1)
for i in range(10):
    array = np.append(array, 1)

print(array)

print("--------------")
array1 = np.ones(10)
print(array1)
print(array1*4)

print("--------------")

h = np.arange(99)
h.resize((10, 10))
print(h)

print(h[0][0]) #fila, columna
print(h[1][0])
print(h[2][0])

for i in range(10):
    h[i][0]= 1
    
for i in range(10):
    h[i][9]= 1
    
for i in range(10):
    h[9][i]= 1

for i in range(10):
    h[0][i]= 1

print(h)

h[::9, 1::9] = 1
print("experimento")
print(h)


print(p1)


"""Esribe tu código aquí"""
# la salida tiene que ser:
#array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
#      [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#      [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#      [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#      [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#      [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#      [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#      [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#      [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#      [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

[]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
--------------
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
--------------
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98  0]]
0
10
20
[[ 1  1  1  1  1  1  1  1  1  1]
 [ 1 11 12 13 14 15 16 17 18  1]
 [ 1 21 22 23 24 25 26 27 28  1]
 [ 1 31 32 33 34 35 36 37 38  1]
 [ 1 41 42 43 44 45 46 47 48  1]
 [ 1 51 52 53 54 55 56 57 58  1]
 [ 1 61 62 63 64 65 66 67 68  1]
 [ 1 71 72 73 74 75 76 77 78  1]
 [ 1 81 82 83 84 85 86 87 88  1]
 [ 1  1  1  1  1  1  1  1  1  1]]
experimento
[[ 1  1  1  1  1  1  1  1  1  1]
 [ 1 11 12 13 14 15 16 17 18  1]
 [ 1 21 22 23 24 25 26 27 28  1]
 [ 1 31 32 33 34 35 36 37 38  1]
 [ 1 41 42 43 44 45 46 47 4

'Esribe tu código aquí'

In [36]:
h = np.array([])
h.resize((10, 10))
print(h)


h[::9, 0::1] = 1
h[0::1, ::9] = 1
print("experimento: ")
print(h)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
experimento: 
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [1]:
#ejercicio 6

import numpy as np

A = np.array([[1, 2], [1, 1]])
b = np.array([3,2])

print(A)
print(b)


Ainv = np.linalg.inv(A)
print("inversa de A:\n",Ainv)


#busca como np hace la inversa de una matriz
"""Esribe tu código aquí"""

print("Ainv * A= \n",np.dot(Ainv,A)) # la unidad
print("[x , y]= ",np.dot(Ainv,b))  #solución 1,1

[[1 2]
 [1 1]]
[3 2]
inversa de A:
 [[-1.  2.]
 [ 1. -1.]]
Ainv * A= 
 [[1. 0.]
 [0. 1.]]
[x , y]=  [1. 1.]
